version: "3"

services:

  php-fpm:
    image: php:8.2.7-fpm-alpine
    container_name: phpfpm
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ${WWW_DOCUMENT_ROOT}/:/app

  nginx:
    image: bitnami/nginx:1.22.1
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/logs:/opt/bitnami/nginx/logs/
      - ./nginx/server-blocks/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro
      - ${WWW_DOCUMENT_ROOT}/:/app
    depends_on:
      - php-fpm
